- name: php
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.3'
    extensions: imagick, swoole
on:
   push:
    branches: [main, develop]
  pull_request:
      branches: [main, develop]

jobs:
  testing:
      runs-on: ubuntu-latest
      steps: 
          - name: Checkout repo 
          - uses: action/checkout@v4  #git clone into runner 
        
          - name: Setup Nodejs
            uses: action/setup-node@v4 # instalar node 
              with: 
                  node-version: 20.x

          - name: Run unit and integrate tests
          - run: go test -v

          - name: Run build
          - run: go build -v

          - name: CI Successful Ok
            if: success()
            uses: rtCamp/action-slack-notify@v2
            with:
              status: 'passed'
              text: 'Go CI succesfully.'
            env:
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

            name: Slack Notification Demo
            jobs:
              slackNotification:
                name: Slack Notification
                runs-on: ubuntu-latest
                steps:
                - uses: actions/checkout@v2
                - name: Slack Notification
                  uses: rtCamp/action-slack-notify@v2
                  env:
                    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            name: PHP Linting
              on: pull_request
              jobs:
                phplint:
                  runs-on: ubuntu-latest
                  steps:
                      - uses: actions/checkout@v1
                      - uses: michaelw90/PHP-Lint@master

          #- name: Run code linter
          #- run: npm run lint
